title: <Aqui vai o título geral>
author: anamauad
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This page was created while learning to add a github page. This is
  an experimental page.

# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  anamauad

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima